server:
  port: 8441
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: "classpath:keystores/client-keystore.p12"
    key-store-password: changeit
    key-alias: client
    key-password: changeit
