server:
  port: 8888 
  
spring:
  application:
   name: config-server
  cloud:
    config: 
      server:
        git:
          uri: https://github.com/sriram5795/Springboot-Demo-Projects-Configs-Store.git
          search-paths: config-server first approach/configs/
          username: xyz@gmail.com
          password: xyz

          
#Details for registering in eureka          
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}         