server:
  port: 8444
#  ssl:
#    key-store-type: PKCS12
#    key-store: "classpath:keystore/test_keystore.p12"
#    key-store-password: changeit
#    key-alias: rootCA
#    key-password: changeit
#    enabled: true

logging:
  level:
    org: DEBUG
