eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
---
server:
  port: 8761
  
spring:
  profiles: peer1
eureka:
  instance:
    hostname: eureka1
  client:
    fetchRegistry: true
    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    
#       defaultZone: http://localhost:8762/eureka/
---
server:
  port: 8762
  
spring:
  profiles: peer2
eureka:
  instance:
    hostname: eureka2
  client:
    fetchRegistry: true
    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    
#       defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8763
  
spring:
  profiles: peer3
eureka:
  instance:
    hostname: eureka3
  client:
    fetchRegistry: true
    registerWithEureka: true
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    
#       defaultZone: http://localhost:8761/eureka/