server: 
  port: 8765
  
spring:
  application:
    name: Zuul-Server

zuul:
  prefix: /api
  routes:
    microservice-one:
      path: /one/**
      service-id: microservice-one
    microservice-two:
      path: /two/**
      service-id: microservice-two
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka