server:
  port: 58081

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          springboot-demo-client:
#            client-id: "SpringBootDemo"
#            client-secret: "password"
#            provider: "keycloak-oauth-provider"
#            authorization-grant-type: "client_credentials"
#
#        provider:
#          keycloak-oauth-provider:
#            authorization-uri: "http://localhost:8080/auth/realms/SpringDemo/protocol/openid-connect/auth"
#            token-uri: "http://localhost:8080/auth/realms/SpringDemo/protocol/openid-connect/token"
#            user-info-uri: "http://localhost:8080/auth/realms/SpringDemo/protocol/openid-connect/userinfo"
#            jwk-set-uri: "http://localhost:8080/auth/realms/SpringDemo/protocol/openid-connect/certs"

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuerUri: http://127.0.0.1:8080/auth/realms/SpringDemo
        registration:
          keycloak:
            grantType: client_credentials
            clientId: SpringBootDemo
            clientSecret: DTxjMJ1H5bwrONWwpxDVTpSQpRrcFIc4
            accessTokenUri: http://127.0.0.1:8080/auth/realms/SpringDemo/protocol/openid-connect/token