server:
  port: 8442
  ssl:
    key-store: "classpath:keystore/test_keystore.p12"
    key-store-type: PKCS12
    key-store-password: changeit
    key-alias: rootCA
    key-password: changeit
    enabled: true