spring:
  datasource:
    url: jdbc:mysql://localhost:33060/BATCH_REPO
    username: batch_user
    password: batch_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: ALWAYS #Creates the Job Repository Related Tables To Save Job Status - Metadata
    job:
      enabled: false #At App Startup Do Not Run The Jobs