spring:
  datasource:
    url: jdbc:mysql://localhost:33060/BATCH_REPO
    username: batch_user
    password: batch_user
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: ALWAYS