server:
  port: 8441
  ssl:
    enabled: true

    key-store-type: JKS
    key-store: "classpath:keystore/client-keystore.jks"
    key-store-password: changeit
    key-alias: client
    key-password: changeit


    trust-store: "classpath:keystore/client-truststore.jks"
    trust-store-type: JKS
    trust-store-password: changeit
    client-auth: need
