server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: "classpath:keystores/server-keystore.p12"
    key-store-password: changeit
    key-alias: server
    key-password: changeit

