server:
  port: 8443
  ssl:
    enabled: true

    key-store-type: JKS
    key-store: "classpath:keystore/server-keystore.jks"
    key-store-password: changeit
    key-alias: server
    key-password: changeit


    trust-store: "classpath:keystore/server-truststore.jks"
    trust-store-type: JKS
    trust-store-password: changeit
    client-auth: need